export const ActionTypes = {
    SET_ALL_USERS: 'SET_ALL_USERS',
    SET_PAGE: 'SET_PAGE',
    SET_LOADING: 'SET_LOADING',
    SET_SELECTED_USER: 'SET_SELECTED_USER',
    REMOVE_USER: 'REMOVE_USER',
    SET_SELECTED_USERS_HISTORY: 'SET_SELECTED_USERS_HISTORY',
    SET_USER_FRIENDS: 'SET_USER_FRIENDS',
    SET_FRIENDS_PAGE: 'SET_FRIENDS_PAGE',
    SET_FRIENDS_LOADING: 'SET_FRIENDS_LOADING'
}